The Newyork Times Article
marcelomaidden/newyorktimes_microverse pull request #1
Opened 2020-09-23 17:33 UTC by imran5644

## the Newyork times clone
in this project we used :
1 Navigation bar
2. floats
3. position
4. grid
5. flexbox
6. footer
7 . aside section
8. images and video

2020-09-23 18:08 UTC, javitocor requested changes
# STATUS: CHANGES REQUIRED ♻️ 

Team, good job so far with this project! 👍 
Your linters are green 🟢 
Your code is clean ! 👏 
You use semantic HTML tags properly 💯 

However, there are some things to improve before approving the project! 
Check my comments below 👇 , apply the required changes and resubmit your project for a new code review 📑 

Good luck with it, keep the good work up ! 😃 

If you have any question or doubt, reach me out on Slack.

## CHANGES

- Your website has an horizontal scrollbar, please check your containers to check which one is causing that and modify it
- Navbar
   - 'Space and cosmos' and the new york times logo must be a link. Kindly fix it
   - Respect the height of the original
   - Please, modify the positioning of the subscribe and login buttons to make them equal to the original, now there is too much space from the top and right side of the screen.
- The text under the main image should be align with the image.
- Main content must be centered, now it is not completely centered, please fix it
- Please modify font size of the main content match the original
- Kindly, modify the space between paragraphs by adding a bit of margin to them.
- In the most popular articles section, please modify the font size and the padding, make it similar to the original
- Kindly fix the aside section, should be equal to the original.
- All the social media icons should be links or at least cursor pointer. Also add them the background and the hover effect.
- In your readme file, acknowledgments section, do not show your links, add text as a link, just like with your live demo link

2020-09-23 23:14 UTC, teekaytech requested changes
## Status: Changes Required :recycle:

### Hi team :wave: 

**So far, this is looking good. However, some of the issues raised by the previous TSE is yet to be fixed. Let's break things down again:**

**[REQUIRED CHANGES]**

- [ ] Your page is still having a horizontal scroll bar. I'm sure this is caused by one of your paddings or margins from one of your containers. Inspect your page and I believe you should be able to figure out which of the containers is causing the horizontal scroll bar. Please Identify and fix this issue.

- [ ] Observe the first title of your page (check the image below). If at all the title will have to break to the next line, it should align vertically to the left with the first line. 
- From my observation, I can see that you have a separate container for the first line (Space Ripples Reveal Big Bang’s) and another one for the second line (Smoking Gun). This should not be so. The second line is a continuation of the first line. Check the Images below for better understanding:

**Original page** 

![o](https://user-images.githubusercontent.com/26856491/94082654-569c7680-fdf9-11ea-9068-5c66c0222fd2.png)

**Your clone**

![c](https://user-images.githubusercontent.com/26856491/94082665-5ef4b180-fdf9-11ea-916d-449a6943ed1d.png)

Kindly fix this.

- [ ] Compare your `Most Popular` section with the original. Please try to make it look like the original.
- The original version of the `Most Popular` section is having some white spaces to the right. Kindly find a way to add it.
- The link items in the `Most Popular` section are not bolded in the original. Please adjust this.

**Original `Most Popular` section:**

![o](https://user-images.githubusercontent.com/26856491/94083202-94e66580-fdfa-11ea-8b6e-13fffe4315d3.png)


**Your cloner version of `Most Popular` section:**

![y](https://user-images.githubusercontent.com/26856491/94083216-9b74dd00-fdfa-11ea-9e10-8580f0dfe284.png)

**Kindly make all the changes required and request another review when you are done.**

* * *

**_You can reach out to me on twitter (@ola_lere), Github(@teekaytech) or slack (@taofeekolalere )_**

Happy Coding :man_technologist:

2020-09-24 17:15 UTC, jubaan requested changes
# Status: Changes Required :recycle:
## :wave: :wave: Hello team!! Great effort on the project!!

There are still unmet requirements. We should focus on improving the suggested changes.

## Requested changes

### [Mandatory] :red_circle: 

- [x] Image not showing properly. It shows disproportionally.
![image](https://user-images.githubusercontent.com/25774518/94175204-fa1e7300-fe5b-11ea-82e0-80b1e6224d2d.png)

- [ ] Not centered
![image](https://user-images.githubusercontent.com/25774518/94175326-25a15d80-fe5c-11ea-8212-d154fc7d70b1.png)

- [ ] Overflowing section.
![image](https://user-images.githubusercontent.com/25774518/94175440-4c5f9400-fe5c-11ea-9dee-b20987da3842.png)

- [ ] Horizontal scroll. This could be related to the previous issue.

- [ ] NYT logo is not a link
![image](https://user-images.githubusercontent.com/25774518/94175622-87fa5e00-fe5c-11ea-83df-60a9205b9ee5.png)

- [ ] Images should be links.
![image](https://user-images.githubusercontent.com/25774518/94175738-b7a96600-fe5c-11ea-8787-08d3e05d5936.png)

- [ ] Use ```a``` html link tag instead of ```cursor: pointer```. Update elements to links.

### [OPTIONAL]  :large_blue_circle: 

- [ ] Keep CSS DRY. see inline comments

### [Comments] :green_circle: 

- The browser **Inspector Mode** is a great tool to understand what's the website doing under the hood. Also, a way to see if the project will look as intended for bigger or smaller screens. 
The Project has more issues than commented, but they are out of the scope of the project objective, as it doesn't ask us to review for responsiveness. **You may or may not work in this issues, is totally up to you**, but if this persist will cause issues in future projects. To give you an idea:
![image](https://user-images.githubusercontent.com/25774518/94176110-3c947f80-fe5d-11ea-9218-7d68bbfddae9.png)
![image](https://user-images.githubusercontent.com/25774518/94176145-47e7ab00-fe5d-11ea-895a-618e5fe614e2.png)
![image](https://user-images.githubusercontent.com/25774518/94176204-5fbf2f00-fe5d-11ea-9d95-becee0d829ab.png)
![image](https://user-images.githubusercontent.com/25774518/94176286-782f4980-fe5d-11ea-9ee4-717ac5ab56b6.png)
![image](https://user-images.githubusercontent.com/25774518/94177329-fc360100-fe5e-11ea-87c7-84c2eb456cd2.png)


## Keep up the great work :muscle: and Happy Coding :smiley: :computer:!!

2020-09-24 17:20 UTC, jubaan requested changes

2020-09-24 17:20 UTC, jubaan commented on stylesheets/style.css
> +  }
DRY stands for "Don't Repeat Yourself". Keeping the project code dry helps readability and makes it easier to find bugs. Example of how to keep the code DRY.
Improved version of the code above:
```
  .name, 
.aside {
    display: none;
  }
```

2020-09-24 20:11 UTC, teekaytech requested changes
# Status: Changes Required :recycle:

## Hi @imran5644  & @marcelomaidden  :wave: 

### You guys have really done a lot to improve his project. Almost all the changes required by the previous reviewers have been fixed and for that, I commend you :+1:

**However, we still need to make one or two changes before this project can be approved. Kindly check my points below and fix them as necessary.:**

**[REQUIRED CHANGES]**

- [ ] Your live demo link is outdated. The current one does not reflect the recent changes you've made. Kindly update your live demo link.

- [ ] There's a line under the `Editors' Pick` section. This is not the case in the original version. Kindly remove the line.

Here's your clone

![o](https://user-images.githubusercontent.com/26856491/94194976-59a36f80-feaa-11ea-82d9-5ade2d7e9646.png)


...and here's the original

![y](https://user-images.githubusercontent.com/26856491/94195006-6031e700-feaa-11ea-9526-2aa6bd9fbb88.png)


**Kindly make all the changes required and request another review when you are done.**

* * *

**_You can reach out to me on twitter (@ola_lere), Github(@teekaytech) or slack (@taofeekolalere )_**

Happy Coding :man_technologist:

2020-09-24 20:38 UTC, teekaytech approved these changes
# Status: Approved :green_circle: 

### Congratulations team, this project has passed all the mandatory requirements. It is therefore approved :heavy_check_mark:

**Comment(s)**
- In your next project, take some time to understand the project requirements well and pay more attention to details. It will help you a great deal as you move on in your journey to become a world-class developer.

Again, congratulations, you can merge to master.
Good luck with your next project.

**I'm @taofeekolalere on slack.
Happy Coding :man_technologist:**

2020-09-24 20:48 UTC, merged